#!/usr/bin/env bash

cleanup() {
	rm "$FIFO_UEBERZUG" 2>/dev/null
	pkill -KILL -P $$
}

if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
	lf $@
else
	export FIFO_UEBERZUG="/tmp/lf-ueberzug-${PPID}"
	mkfifo "$FIFO_UEBERZUG"
	trap cleanup EXIT
	tail --follow "$FIFO_UEBERZUG" | ueberzug layer --silent --parser bash &
	lf $@
fi
