#!/usr/bin/env bash
export FIFO_UEBERZUG="/tmp/lf-ueberzug-${PPID}"
export LAST_PIC_FILE="/tmp/last_ueberzug_img-${PPID}"

function cleanup {
	rm "$FIFO_UEBERZUG" 2>/dev/null
	pkill -P $$
}

touch $LAST_PIC_FILE
mkfifo "$FIFO_UEBERZUG"
trap cleanup EXIT
tail --follow "$FIFO_UEBERZUG" | ueberzug layer --silent --parser bash &

lf
